### ISSUE TITLE
[Bug] After 3.7.0 release WhatsApp and Discord data is deleted, although all options are enabled

### ISSUE THREAD

**Issue by sojusnik** [mrdokenny/Cookie-AutoDelete#1395]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

After updating to v3.7.0 of CAD, WhatsApp and Discord data is deleted, so you have to log in again after a browser restart, although all options are enabled, as shown in the following pictures:

![grafik](https://user-images.githubusercontent.com/1245718/170009346-0e795d37-c7e4-49dc-af82-e80877e84fa4.png)
![grafik](https://user-images.githubusercontent.com/1245718/170009421-1ab49c13-83ed-4aae-aa23-5481656ecce1.png)

WhatsApp is opened and set up in a named container (f.i. Social Media), while Discord uses the default container (= no container).
Other pages where you have to log in, like GitHub or Gmail, are still working properly (like WhatsApp and Discord worked before v3.7.0), so you don't have to log in each time after the browser is closed.

### To Reproduce

1. Import my [CAD_CoreSettings_2022-05-24_12.25.36.json](https://mega.nz/file/XtJ3gDgC#jyHgyTna4xLHs1KZTYanVwDxS4F_etrREV12J6-Diy4)
2. Set up the CAD rules taking into account the bug description above
3. log in into WhatsApp and Discord
4. Close browser
5. Open browser and check WhatsApp and Discord

### Expected Behavior

CAD shouldn't delete the data on sites like WhatsApp and Discord, so you don't have to log in each time after the browser was closed.

### System Info - Operating System (OS)

Ubuntu 21.10

### System Info - Browser Info

Firefox 100.0.2

### System Info - CookieAutoDelete Version

3.7.0

**Comment by bxkx** [comment]
I don't use WhatsApp but I'm having the same issue with Discord.
There are also some minor issues with YouTube forgetting the set video quality and subtitle settings. Sonarr also loses the calendar ordering settings. Haven't noticed anything else yet

Edit: Realized it's also happening with the Steam web chat. I'm logged in but the settings are reset every time.

**Comment by sojusnik** [comment]
> There are also some minor issues with YouTube forgetting the set video quality and subtitle settings.

I think that was the issue even with pre v3.7.0.

**Comment by bxkx** [comment]
I never experienced that before the update.

**Comment by olidie** [comment]
Experiencing the same problem with WhatsApp. Threema and feedly are also affected in my case. Slack is working fine.

**Comment by M0rPh1X** [comment]
Same Problem with BetterTTV settings on Twitch

**Comment by frank-owen** [comment]
Cleanup logs show some site data, including 0 cookies being removed despite everything being whitelisted. It appears to be local storage that is being removed incorrectly while cookies remain unaffected. On some sites this is resetting settings other (such as discord) this appears enough to force a log out).

![image](https://user-images.githubusercontent.com/103252937/170093331-0f22eb8d-1eab-4e95-9e55-7bee0d04d380.png)
![image](https://user-images.githubusercontent.com/103252937/170093453-be23fcda-cd40-4ee8-bc84-2a93c4864b7c.png)

Also to note this is observed in Firefox and Brave/Chromium.

**Comment by MyNameIsNotListed** [comment]
Can confirm the issue for Discord in Google Chrome, stopped logging out by disabling the option `Enable LocalStorage Cleanup`.
![CAD](https://user-images.githubusercontent.com/95109651/170153246-697462a4-580e-44d4-add1-6d176ac37a48.png)

**Comment by lyaaz** [comment]
same problem here on github.com.
firefox 100.0.2
CAD 3.7.0

**Comment by mrjohnjones** [comment]
Same problem. Using the latest Firefox 100.0.2. I have the problem with ProtonMail's new domain, proton.me. 

However, this happens only if I had proton.me open in a tab while exiting the browser completely. When I start the browser next time, it deletes the cookie data for proton.me even though I have rules not to. If I close the proton.me tab before exiting the browser, the proton.me cookie data it NOT deleted on browser restart as expected or even tab close.

This problem does not happen if I have the option turned off: "Enable Greylist Cleanup on Browser Restart". Although I have no Greylists, with this option off, nothing is cleaned on restart (sites with no rules) so I need it on. I'm not sure how the greylist option effects this since proton.me's domains are in a whitelist.

Anyway, I hope this information helps.

**Comment by kennethtran93** [comment]
Apologies everybody - seems trying to fix site data cleanup on restart affected the check.  I'll look into it as soon as possible.

Thanks for all the reports.

**Comment by kennethtran93** [comment]
> Can confirm the issue for Discord in Google Chrome, stopped logging out by disabling the option `Enable LocalStorage Cleanup`. ![CAD](https://user-images.githubusercontent.com/95109651/170153246-697462a4-580e-44d4-add1-6d176ac37a48.png)

Please keep in mind that when you check that box again, all your existing localstorage data WILL be removed.

**Comment by Rafael-Ramblas** [comment]
Can confirm the issue with whatsapp web

**Comment by led9** [comment]
Hello, your NEW version DELETE all my save settings for sites (This is not scary for me, I restored it from the saved copy, but I had to roll back the version of your extension, please fix it.)

Im use extension Greasemonkey and user script with it - "Adblock+".
The script allows you to select and delete the any element of any site. Information about my choice of what exactly to delete from the site is preserved between the sessions in the folder with the name of the site here:
Mozilla\Firefox\Profiles\ * **.default\storage\default
for this site is folder
Mozilla\Firefox\Profiles\ * **.default\storage\default\https+++github.com, contains:
file .metadata-v2
folder "Is" with files data.sqlite and usage. 

The previous version of your extension did not change anything in these folders.

When removing the history in Firefox, I do not delete the “Autonomous Websites data”, this made it possible to preserved these settings for "Greasemonkey and user script with it - "Adblock+"" until your extension intervened and deleted everything.

So, your extension, apparently, climbed and deleted something from the contents of these folders - Moreover, the folders themselves remain, maybe the files in them too, but my sites settings are deleted by your extension! For some reason, your extension began to clean the contents of these files.
do it so that your extension does not do that.

Your extension is good And I hope you fix it.

**Comment by kennethtran93** [comment]
I'm working on a fix, and a new option to _not_ delete existing data on site data types when toggled on.

**Comment by kennethtran93** [comment]
Those that want to help try/test the PR patch can head to the linked PR and request a build download following the bot command in that message.  You will also need to ensure `xpinstall.signatures.required` is set to `false` on Firefox, unsure if anything needs to be done in chrome before manual installation.

My apologies about the unintentional site data cleanup on restart.

**Comment by EchoDev** [comment]
I'm on 3.8.0 and I think the bug is not fixed? Can anyone else confirm?

**Comment by hugoghx** [comment]
+1. Just enabled the LocalStorage option again and it wiped all the data, including from my whitelisted domains. Is this expected behaviour? The warning does say that "ALL existing data for that type will be cleared.". Is ALL meant to be taken literally here?

If so, what changed? Before 3.7.0, at least as far as I can tell (and correct me if I'm wrong here), LocalStorage was not being cleaned on whitelisted domains.

**Comment by adorack** [comment]
I can't speak to the history, but at least for me, 3.8 seems to have fixed the problem: I'm no longer losing LocalStorage for whitelisted sites.  (Thanks for fixing this!)

> Just enabled the LocalStorage option again and it wiped all the data, including from my whitelisted domains. Is this expected behaviour?

I think this is expected behavior when you _first_ enable a checkbox for cleaning.  As of 3.8, there's a new opt-in setting to prevent cleaning LocalStorage when you check the "clean LocalStorage" box for the first time, but it comes with tradeoffs -- docs are here: https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#clean-existing-data-for-newly-enabled-browsing-data-types.

**Comment by kennethtran93** [comment]
> +1. Just enabled the LocalStorage option again and it wiped all the data, including from my whitelisted domains. Is this expected behaviour? The warning does say that "ALL existing data for that type will be cleared.". Is ALL meant to be taken literally here?
> 
> If so, what changed? Before 3.7.0, at least as far as I can tell (and correct me if I'm wrong here), LocalStorage was not being cleaned on whitelisted domains. 

@hugoamvieira  Yes. ALL is taken literally here. Primary reason is that we can only query for individual cookies already set. All other browsing data types do NOT have a way for web extensions to query which domain has set something for that data type. All we can do for non-cookie data types is either put in the domain to clean up (which implies that we should already know the domains to clean up, which we can only do after querying all existing cookies) or specify the time frame to clean up (which may clean up the ones you intended to keep if it was used in that time frame) . 

Localstorage not cleaning in whitelisted domains is still a thing. However in 3.7.0 I accidentally introduced a regression bug in the conditional check to determine what site data to clean up, which has been fixed in 3.8.0. Also in 3.8.0 was an added option to not empty the site data type to clean on activation, but does come with a caveat that whatever is currently in there will stay in there, even unwanted ones, unless the unwanted domain either has a cookie available to query/delete and/or it as been visited at least once since the settings change (so that we can generate a cookie)

**Comment by kennethtran93** [comment]
> I'm on 3.8.0 and I think the bug is not fixed? Can anyone else confirm?

@EchoDev what browser are you using, and can you elaborate on what is not fixed? Remember that unless you opt to not clean up existing site data when globally enabling the site data cleanup, it will clear/empty it when you enable the option.

**Comment by Slaash007** [comment]
I still have the issue on twitch.tv (v3.8.0 on Firefox 91.10.0esr/Windows).

As "Enable LocalStorage Cleanup" is on, whenever I close my twitch tab or close Firefox and come back on the site, I will lose my display settings (night mode, chat display). I've tried to open the site, set my display then close and come back multiple times. So it should not be due to the option "Clean Existing Data for Newly Enabled Browsing Data Types".

If I disable "Enable LocalStorage Cleanup", it will keep the twitch display settings whenever I come back on the site.

**Comment by EchoDev** [comment]
I can confirm what @Slaash007 writes. I have the exact same issue, losing settings (dark theme etc.) on twitch

**Comment by kennethtran93** [comment]
What expression entry have you guys set for twitch, and whether or not you are logged in or not.

**Comment by EchoDev** [comment]
@kennethtran93 I reset my settings, seems to be working ok now. If I run into issues I will report with settings!

**Comment by Slaash007** [comment]
@kennethtran93 :
Domain: twitch.tv
Options: all checked
Type: Whitelist

And logged in.

@EchoDev , you mean uninstall CAD then reinstall, or just remove twitch expression and set again ?

**Comment by EchoDev** [comment]
@Slaash007 I basically removed all rules and then reset all settings to default within CAD (There is a button for it)
Then reconfigged the extension

**Comment by Slaash007** [comment]
OK. I've done the same thing as @EchoDev (restore default settings + delete expressions and reset all the same as before) and everything works fine now.

**Comment by hugoghx** [comment]
^^ Did the same, works as before 3.7.0 now. I think there may be some problems with using old configuration across CAD versions - at least these last two

**Comment by Slaash007** [comment]
My twitch display settings are gone today. The issue is still reproductible. 😕

**Comment by wkral** [comment]
I'm still getting local storage being deleted for a whitelisted domain, I've reset the settings, which didn't work for me and reinstalled the plugin and reset the settings still seeing local storage being deleted. I'm alsu using containers, so maybe that's adding to the issue? It seems that it's maybe happening when a legitimate expired cookie is cleaned up. Unfortunately a service I'm using switched to local storage for their login session, so I'm forced to log back in regularly.

**Comment by kennethtran93** [comment]
> I'm still getting local storage being deleted for a whitelisted domain, I've reset the settings, which didn't work for me and reinstalled the plugin and reset the settings still seeing local storage being deleted. I'm alsu using containers, so maybe that's adding to the issue? It seems that it's maybe happening when a legitimate expired cookie is cleaned up. Unfortunately a service I'm using switched to local storage for their login session, so I'm forced to log back in regularly.

If you are using containers, it is __strongly advised__ to ensure that you are only accessing the configured domain inside that specific container that has the expression.  Firefox does have an extension that you can use to force all attempts to access a specific domain to only open in the one container.  A warning exists in the settings that warn you if cookies/domains are found for a container that requires its site data to be removed (with/without expression configured) for that container, it will affect __ALL__ containers.  This is not a CAD bug, but rather the limitations of the WebExtension API.



At the time of this post, the only site data aside from cookies that Firefox has implemented to limit the site data cleared by container is `indexeddb`.

![image](https://user-images.githubusercontent.com/6724477/179381866-5a4d71de-7c69-4535-a232-74ad8f9ddf52.png)

We have not implemented any of the site data being cleaned by containers yet as it does not apply to majority of the items. Localstorage, as stated in the screenshot, may specify a container but only when using Firefox Nightly, which we are not officially supporting at this time as the codebase continuously changes as bugs are squashed and features are added.

**Comment by wkral** [comment]
Thanks for the reply, I'm definitely only accessing the domain within the specified container with the expression.

It's been fairly time consuming to test, there seems to be a cookie set with an expiry somewhere between 30 minutes and a few hours from the time of creation shortly after logging in. That cookie doesn't seem to have anything to do with the login session for the site. I've observed a few times that after the expiry of that cookie a log entry in CAD stating that it's cleaning up the domain and deleting that specific cookie. After this when I look in the developer tools storage section in FF, and the local storage items are gone, one being the login session token.

I ran the experiment again with "Clean All Expired Cookies" setting off, and as expected there is no log entry after the expiration. The local storage also remains intact after the expiration. So it seems that cleanup of the domain for expired cookies also deletes the local storage for that domain even if it is explicitly whitelisted.

I could see this being considered a separte issue, so I'd be happy to open a new one if you'd like.

**Comment by kennethtran93** [comment]
> Thanks for the reply, I'm definitely only accessing the domain within the specified container with the expression.
> 
> It's been fairly time consuming to test, there seems to be a cookie set with an expiry somewhere between 30 minutes and a few hours from the time of creation shortly after logging in. That cookie doesn't seem to have anything to do with the login session for the site. I've observed a few times that after the expiry of that cookie a log entry in CAD stating that it's cleaning up the domain and deleting that specific cookie. After this when I look in the developer tools storage section in FF, and the local storage items are gone, one being the login session token.
> 
> I ran the experiment again with "Clean All Expired Cookies" setting off, and as expected there is no log entry after the expiration. The local storage also remains intact after the expiration. So it seems that cleanup of the domain for expired cookies also deletes the local storage for that domain even if it is explicitly whitelisted.
> 
> I could see this being considered a separte issue, so I'd be happy to open a new one if you'd like.

do open a new issue for this please.
